# Generated by Django 4.2.7 on 2023-12-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg', models.FloatField()),
                ('gluc', models.FloatField()),
                ('blood', models.FloatField()),
                ('skin', models.FloatField()),
                ('ins', models.FloatField()),
                ('bmi', models.FloatField()),
                ('dbf', models.FloatField()),
                ('age', models.FloatField()),
                ('prediction', models.CharField(max_length=255)),
            ],
        ),
    ]
